# Problem 10: Custom Iterator for Paginated Data

# Create a custom iterator named Paginator that divides a list of items into fixed-size pages.

# Requirements:
# - Create a Paginator class.
# - Accept a list of items and a page size through the constructor.
# - Implement __iter__() and __next__().
# - Each call to next() should return the next page as a list.
# - The final page may contain fewer elements than the specified page size.
# - Raise StopIteration after all pages have been returned.
# - Test the iterator with at least 12 items and a page size of 3.
# - Display every page generated by the iterator.

class Paginator:
    def __init__(self, items, page_size):
        self.items = items
        self.page_size = page_size
        self.index = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self.index < len(self.items):
            page = self.items[self.index:self.index + self.page_size]
            self.index += self.page_size
            return page
        else:
            raise StopIteration


# Create a list of items
items = [
    "Apple",
    "Banana",
    "Mango",
    "Orange",
    "Grapes",
    "Watermelon",
    "Pineapple",
    "Papaya",
    "Guava",
    "Strawberry",
    "Kiwi",
    "Cherry",
    "Peach",
    "Pomegranate"
]

# Page size
page_size = 3

# Create Paginator object
paginator = Paginator(items, page_size)

# Display every page
for page in paginator:
    print(page)