Problem 10: Custom Iterator for Paginated Data

Create a custom iterator named Paginator that divides a list of items into fixed-size pages.

Requirements:
- Create a Paginator class.
- Accept a list of items and a page size through the constructor.
- Implement __iter__() and __next__().
- Each call to next() should return the next page as a list.
- The final page may contain fewer elements than the specified page size.
- Raise StopIteration after all pages have been returned.
- Test the iterator with at least 12 items and a page size of 3.
- Display every page generated by the iterator.
